version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  redis_data: